/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twentyoneai;

import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class DataFrame extends javax.swing.JFrame {

    /**
     * Creates new form DataFrame
     */
    public DataFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAIWinsLabel = new javax.swing.JLabel();
        lblAIWins = new javax.swing.JLabel();
        lblTotalGamesLabel = new javax.swing.JLabel();
        lblTotalGames = new javax.swing.JLabel();
        lblWinPercLabel = new javax.swing.JLabel();
        lblWinPerc = new javax.swing.JLabel();
        lblTargetMoveLabel = new javax.swing.JLabel();
        lblTargetMove = new javax.swing.JLabel();
        lblAIMoveLabel = new javax.swing.JLabel();
        lblAIMove = new javax.swing.JLabel();
        lblTotalErrorLabel = new javax.swing.JLabel();
        lblTotalError = new javax.swing.JLabel();
        lblWinningsLabel = new javax.swing.JLabel();
        lblWinnings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Training Data");

        lblAIWinsLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAIWinsLabel.setText("AI Wins: ");

        lblAIWins.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAIWins.setText("0");

        lblTotalGamesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalGamesLabel.setText("Total Games: ");

        lblTotalGames.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalGames.setText("0");

        lblWinPercLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWinPercLabel.setText("AI Win Percentage: ");

        lblWinPerc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWinPerc.setText("0");

        lblTargetMoveLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTargetMoveLabel.setText("Ideal Move: ");

        lblTargetMove.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTargetMove.setText("0");

        lblAIMoveLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAIMoveLabel.setText("AI Move: ");

        lblAIMove.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAIMove.setText("0");

        lblTotalErrorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalErrorLabel.setText("Total Error: ");

        lblTotalError.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalError.setText("0");

        lblWinningsLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWinningsLabel.setText("Total Winnings: $");

        lblWinnings.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWinnings.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWinningsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWinnings))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalErrorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalError))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAIMoveLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAIMove))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTargetMoveLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTargetMove))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWinPercLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWinPerc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalGamesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalGames))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAIWinsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAIWins)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAIWinsLabel)
                    .addComponent(lblAIWins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalGamesLabel)
                    .addComponent(lblTotalGames))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWinPercLabel)
                    .addComponent(lblWinPerc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargetMoveLabel)
                    .addComponent(lblTargetMove))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAIMoveLabel)
                    .addComponent(lblAIMove))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalErrorLabel)
                    .addComponent(lblTotalError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWinningsLabel)
                    .addComponent(lblWinnings))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataFrame().setVisible(true);
            }
        });
    }
    
    
    //Getters and Setters
    
    public JLabel getLblAIMove() {
        return lblAIMove;
    }

    public JLabel getLblAIWins() {
        return lblAIWins;
    }

    public JLabel getLblDealerWins() {
        return lblTotalGames;
    }

    public JLabel getLblTargetMove() {
        return lblTargetMove;
    }

    public JLabel getLblTotalError() {
        return lblTotalError;
    }

    //Getters and Setters
    public JLabel getLblWinPerc() {
        return lblWinPerc;
    }    

    public JLabel getLblWinnings() {
        return lblWinnings;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAIMove;
    private javax.swing.JLabel lblAIMoveLabel;
    private javax.swing.JLabel lblAIWins;
    private javax.swing.JLabel lblAIWinsLabel;
    private javax.swing.JLabel lblTargetMove;
    private javax.swing.JLabel lblTargetMoveLabel;
    private javax.swing.JLabel lblTotalError;
    private javax.swing.JLabel lblTotalErrorLabel;
    private javax.swing.JLabel lblTotalGames;
    private javax.swing.JLabel lblTotalGamesLabel;
    private javax.swing.JLabel lblWinPerc;
    private javax.swing.JLabel lblWinPercLabel;
    private javax.swing.JLabel lblWinnings;
    private javax.swing.JLabel lblWinningsLabel;
    // End of variables declaration//GEN-END:variables
}
